language: node_js
node_js:
  – "7"
dist: trusty
services:
  – mongodb
env:
  – NODE_ENV=product PORT=3000 MONGO_URI=mongodb+srv://tests:test1234@cluster0.n6uhb.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
install:
  – npm install express mongoose --save
  – npm run build
script:
  – nohup npm run start &
  – sleep 3
  – npm run test
